POST http://localhost:8089/register/
Content-Type: application/json

{
    "userName": "user1",
    "password": "pass"
}
###

POST http://localhost:8089/login/
Content-Type: application/json

{
    "userName": "user1",
    "password": "pass"
}
###